/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_android_lcontroller_CaptureScreen */

#ifndef _Included_app_android_lcontroller_CaptureScreen
#define _Included_app_android_lcontroller_CaptureScreen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_android_lcontroller_CaptureScreen
 * Method:    TCPConnect_listen_server
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_app_android_lcontroller_CaptureScreen_TCPConnect_1listen_1server
  (JNIEnv *, jobject, jint);

/*
 * Class:     app_android_lcontroller_CaptureScreen
 * Method:    TCPConnect_accept_client
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_android_lcontroller_CaptureScreen_TCPConnect_1accept_1client
  (JNIEnv *, jobject);

/*
 * Class:     app_android_lcontroller_CaptureScreen
 * Method:    TCPConnect_recv_msg
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_android_lcontroller_CaptureScreen_TCPConnect_1recv_1msg
  (JNIEnv *, jobject);

/*
 * Class:     app_android_lcontroller_CaptureScreen
 * Method:    TCPConnect_send_screen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_android_lcontroller_CaptureScreen_TCPConnect_1send_1screen
  (JNIEnv *, jobject);

/*
 * Class:     app_android_lcontroller_CaptureScreen
 * Method:    TCPConnect_close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_android_lcontroller_CaptureScreen_TCPConnect_1close
  (JNIEnv *, jobject);

/*
 * Class:     app_android_lcontroller_CaptureScreen
 * Method:    getErrorMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_android_lcontroller_CaptureScreen_getErrorMsg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
