/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_android_USBIP_ShellProc */

#ifndef _Included_app_android_USBIP_ShellProc
#define _Included_app_android_USBIP_ShellProc
#ifdef __cplusplus
extern "C" {
#endif
#undef app_android_USBIP_ShellProc_MAX_CLIENT
#define app_android_USBIP_ShellProc_MAX_CLIENT 5L
/*
 * Class:     app_android_USBIP_ShellProc
 * Method:    server_bind
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_app_android_USBIP_ShellProc_server_1bind
  (JNIEnv *, jobject, jint);

/*
 * Class:     app_android_USBIP_ShellProc
 * Method:    listen_client
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_android_USBIP_ShellProc_listen_1client
  (JNIEnv *, jobject);

/*
 * Class:     app_android_USBIP_ShellProc
 * Method:    recv_sock
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_android_USBIP_ShellProc_recv_1sock
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
